import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import AuthProvider from "../../contexts/authContext";
import { CartProvider } from "../../contexts/cartContext";
import { LikeProvider } from "../../contexts/likeContext";

const primaryFont = DM_Sans({
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondaryFont = Inter({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gianoius Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LikeProvider>
      <CartProvider>
        <AuthProvider>
          <html lang="en">
            <body className={`${primaryFont.variable} ${secondaryFont.variable} antialiased flex flex-col min-h-screen`}>
              <nav><Navbar /></nav>
              <main className="bleed flex-1">{children}</main>
              <footer className="mt-auto"><Footer /></footer>
              <ToastContainer />
            </body>
          </html>
        </AuthProvider>
      </CartProvider>
    </LikeProvider>
  );
}
